# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_axi_intc_3/eth1_microblaze_0_axi_intc_3.xci
# IP: The module: 'eth1_microblaze_0_axi_intc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_axi_intc_3/eth1_microblaze_0_axi_intc_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_microblaze_0_axi_intc_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_axi_intc_3/eth1_microblaze_0_axi_intc_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_microblaze_0_axi_intc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_axi_intc_3/eth1_microblaze_0_axi_intc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_microblaze_0_axi_intc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_axi_intc_3/eth1_microblaze_0_axi_intc_3.xci
# IP: The module: 'eth1_microblaze_0_axi_intc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_axi_intc_3/eth1_microblaze_0_axi_intc_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_microblaze_0_axi_intc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_axi_intc_3/eth1_microblaze_0_axi_intc_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_microblaze_0_axi_intc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_microblaze_0_axi_intc_3/eth1_microblaze_0_axi_intc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_microblaze_0_axi_intc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
