# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_dma_0_0/eth1_axi_dma_0_0.xci
# IP: The module: 'eth1_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_dma_0_0/eth1_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_dma_0_0/eth1_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_dma_0_0/eth1_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_dma_0_0/eth1_axi_dma_0_0.xci
# IP: The module: 'eth1_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_dma_0_0/eth1_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_dma_0_0/eth1_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/dario/fulgor/trabajo_final/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_axi_dma_0_0/eth1_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
