# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/eth1_system_ila_0_0.xci
# IP: The module: 'eth1_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/bd_9386.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9386 || ORIG_REF_NAME==bd_9386} -quiet] -quiet

# IP: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/ip/ip_0/bd_9386_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9386_ila_lib_0 || ORIG_REF_NAME==bd_9386_ila_lib_0} -quiet] -quiet

# IP: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/ip/ip_1/bd_9386_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9386_g_inst_0 || ORIG_REF_NAME==bd_9386_g_inst_0} -quiet] -quiet

# XDC: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9386_ila_lib_0 || ORIG_REF_NAME==bd_9386_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9386_ila_lib_0 || ORIG_REF_NAME==bd_9386_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/ip/ip_0/bd_9386_ila_lib_0_ooc.xdc

# XDC: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/bd_9386_ooc.xdc

# XDC: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/eth1_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/eth1_system_ila_0_0.xci
# IP: The module: 'eth1_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/bd_9386.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9386 || ORIG_REF_NAME==bd_9386} -quiet] -quiet

# IP: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/ip/ip_0/bd_9386_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9386_ila_lib_0 || ORIG_REF_NAME==bd_9386_ila_lib_0} -quiet] -quiet

# IP: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/ip/ip_1/bd_9386_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9386_g_inst_0 || ORIG_REF_NAME==bd_9386_g_inst_0} -quiet] -quiet

# XDC: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9386_ila_lib_0 || ORIG_REF_NAME==bd_9386_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9386_ila_lib_0 || ORIG_REF_NAME==bd_9386_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/ip/ip_0/bd_9386_ila_lib_0_ooc.xdc

# XDC: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/bd_0/bd_9386_ooc.xdc

# XDC: /home/becario/ethernet/TPF-Fulgor-2020/Ethernet/ethernet_base_v2019/ethernet_GMII_v1.srcs/sources_1/bd/eth1/ip/eth1_system_ila_0_0/eth1_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth1_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
